-- Đăng nhập với sys/12345 để thực hiện
ALTER PLUGGABLE DATABASE ATBMCQ_16_CSDL OPEN READ WRITE;
ALTER SESSION SET CONTAINER = ATBMCQ_16_CSDL;

SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security';
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS';
---> BẬT OLS NẾU CHƯA BẬT/ CHƯA ĐĂNG KÝ THÌ ĐĂNG KÝ OLS VÀ BẬT OLS
-- This procedure registers Oracle Label Security.EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS; -- This procedure enables it
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
---> KHỞI ĐỘNG LẠI
SHUTDOWN IMMEDIATE;
STARTUP;

ALTER SESSION SET CONTAINER = CDB$ROOT;
---> UNLOCK LBACSYS (OLS ADMIN)
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;
---> CHUYỂN QUA PDB
ALTER SESSION SET CONTAINER= ATBMCQ_16_CSDL;
--TẠO USER TEST OLS = ADMIN_OLS
---> TẠO ADMIN OLS & CẤP QUYỀN CHO ADMIN_OLS

CREATE USER ADMIN_OLS IDENTIFIED BY 123 CONTAINER = CURRENT;
GRANT CONNECT,RESOURCE TO ADMIN_OLS; --CẤP QUYỀN CONNECT VÀ RESOURCE
GRANT UNLIMITED TABLESPACE TO ADMIN_OLS; --CẤP QUOTA CHO ADMIN_OLS
GRANT SELECT ANY DICTIONARY TO ADMIN_OLS; --CẤP QUYỀN ĐỌC DICTIONARY
---> CẤP QUYỀN EXECUTE CHO ADMIN_OLS
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_user_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_label_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON char_to_label TO ADMIN_OLS WITH GRANT OPTION;

---> ADD ADMIN_OLS VÀO LBAC_DBA
GRANT LBAC_DBA TO ADMIN_OLS;
GRANT EXECUTE ON sa_sysdba TO ADMIN_OLS;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN_OLS; -- CẤP QUYỀN THỰC THI

commit;

--B4: CONNECT SYS KIỂM TRA COMPONENT TẠO ĐÚNG CHƯA
SELECT * FROM DBA_SA_LEVELS;
SELECT * FROM DBA_SA_COMPARTMENTS;
SELECT * FROM DBA_SA_GROUPS;
SELECT * FROM DBA_SA_GROUP_HIERARCHY;

-- KIỂM TRA 
SELECT * FROM DBA_SA_USER_LEVELS WHERE POLICY_NAME = 'THONGBAO_POLICY';
SELECT * FROM DBA_SA_USER_COMPARTMENTS WHERE POLICY_NAME = 'THONGBAO_POLICY';
SELECT * FROM DBA_SA_USER_GROUPS WHERE POLICY_NAME = 'THONGBAO_POLICY';

-- KIỂM TRA 
SELECT * FROM DBA_SA_USER_LABELS;

-- KIỂM TRA 
SELECT * FROM dba_sa_labels;


SELECT * FROM ADMIN_OLS.THONGBAO;