BEGIN
SA_SYSDBA.CREATE_POLICY(
policy_name => 'region_policy',
column_name => 'region_label');
END;

--ENABLE POLICY VỪA TẠO -> KHOI DONG LẠI SQLDEV
EXEC SA_SYSDBA.ENABLE_POLICY ('region_policy');
--TẠO COMPONENT CỦA LABEL
--->TẠO LEVEL
EXECUTE SA_COMPONENTS.CREATE_LEVEL('region_policy',20,'L1','LEVEL 1');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('region_policy',40,'L2','LEVEL 2');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('region_policy',60,'L3','LEVEL 3');
--->TẠO COMPARTMENT
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('region_policy',100,'M','MANAGEMENT');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('region_policy',120,'E','EMPLOYEE');
--->TẠO GROUP
EXECUTE SA_COMPONENTS.CREATE_GROUP('region_policy',20,'R20','REGION NORTH');
EXECUTE SA_COMPONENTS.CREATE_GROUP('region_policy',40,'R40','REGION SOUTH');
EXECUTE SA_COMPONENTS.CREATE_GROUP('region_policy',60,'R60','REGION EAST');
EXECUTE SA_COMPONENTS.CREATE_GROUP('region_policy',80,'R80','REGION WEST');

CREATE TABLE OLS_KHACHHANG
(
ID NUMBER(10),
CUST_TYPE VARCHAR2(10),
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30),
REGION VARCHAR2(30),
CREDIT NUMBER(10,2),
PRIMARY KEY(ID)
);

INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(1,'SILVER', 'HARRY','HILL','NORTH',11000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(2,'SILVER','VIC','REEVES','NORTH',2000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(3,'SILVER','BOB','MORTIMER','WEST',500);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(4,'SILVER','PAUL','WHITEHOUSE','SOUTH',1000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(5,'SILVER','HARRY','ENFIELD','EAST',20000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(6,'GOLD','JENIFER','LOPEZ','WEST',500);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(7,'GOLD','KYLIE','MINOGUE','NORTH',1000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(8,'GOLD','MARIA','CAREY','WEST',1000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(9,'GOLD','DANI','MINOGUE','SOUTH',20000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(10,'GLOD','WHITNEY','HOUSTON','EAST',500);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(11,'PLATINUM','ROBBIE','WILLIAMS','SOUTH',500);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(12,'PLATINUM','THOM','YORKE','NORTH',2000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(13,'PLATINUM','GARETH','GATES','WEST',10000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(14,'PLATINUM','DARIUS','DINESH','EAST',2000);
INSERT INTO OLS_KHACHHANG(ID,
CUST_TYPE,FIRST_NAME,LAST_NAME,REGION,CREDIT)
VALUES(15,'PLATINUM','WILL','YOUNG','EAST',100);
SELECT * FROM OLS_KHACHHANG;

--B7: CẬP NHẬT NHÃN TRONG BẢNG
BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
POLICY_NAME => 'REGION_POLICY',
SCHEMA_NAME => 'ADMIN_OLS',
TABLE_NAME => 'OLS_KHACHHANG',
TABLE_OPTIONS => 'NO_CONTROL'
);
END;

--B6:TẠO NHÃN
----TẠO THỦ CÔNG BẰNG LỆNH
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L3:E:R20')
WHERE ID = 1;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L2:E:R20')
WHERE ID = 2;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L1:E:R80')
WHERE ID = 3;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L2:E:R40')
WHERE ID = 4;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L3:E:R60')
WHERE ID = 5;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L1:E:R80')
WHERE ID = 6;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L2:E:R20')
WHERE ID = 7;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L2:E:R80')
WHERE ID = 8;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L2:E:R40')
WHERE ID = 9;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L1:E:R60')
WHERE ID = 10;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L1:M:R40')
WHERE ID = 11;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L2:M:R20')
WHERE ID = 12;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L3:M:R80')
WHERE ID = 13;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L2:M:R60')
WHERE ID = 14;
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L1:M:R60')
WHERE ID = 15;

    UPDATE OLS_KHACHHANG
    SET region_label = CHAR_TO_LABEL('REGION_POLICY','L1')
    WHERE ID = 15;

--B8: UPDATE ĐỂ KHỞI TẠO LABEL TRONG BẢNG OLS_KHACHHANG (OPTION=NO_CONTROL)
UPDATE OLS_KHACHHANG
SET region_label = CHAR_TO_LABEL('REGION_POLICY','L1');

SA_POLICY_ADMIN.POLICY_SUBSCRIBE('region_policy');
--B9: ÁP DỤNG OLS VÀO BẢNG
BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
    policy_name => 'REGION_POLICY',
    schema_name => 'ADMIN_OLS',
    table_name => 'OLS_KHACHHANG',
    table_options => 'READ_CONTROL',
    predicate => NULL
);
END;

commit;

--TSST XÓA CHÍNH SÁCH
BEGIN
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('REGION_POLICY','ADMIN_OLS','OLS_KHACHHANG');
END;




--B10:UPDATE BẢNG OLS_KHACHHANG (ĐỂ GỌI UPDATE LABEL)
UPDATE OLS_KHACHHANG
SET first_name = first_name;
COMMIT;

--B11: TẠO USER ĐỂ TEST (CONNECT VÀO SYS)
CREATE USER sales_manager IDENTIFIED BY 123;
CREATE USER sales_north IDENTIFIED BY 123;
CREATE USER sales_south IDENTIFIED BY 123;
CREATE USER sales_east IDENTIFIED BY 123;
CREATE USER sales_west IDENTIFIED BY 123;

--B12: CẤP QUYỀN CONNECT CHO CÁC TÀI KHOẢN TEST (CONNECT VÀO SYS)
GRANT CONNECT TO sales_manager;
--sales_north, sales_south, sales_east, sales_west;
GRANT SELECT ON ADMIN_OLS.OLS_KHACHHANG TO sales_manager;
--, sales_north,sales_south, sales_east, sales_west;

--B13:GÁN LABEL CHO USER
BEGIN
SA_USER_ADMIN.SET_USER_LABELS('region_policy','sales_manager','L3:M,E:R20,R40,R60,R80');
END;

SA_USER_ADMIN.SET_USER_LABELS('region_policy','sales_north','L3:E:R20,R40');
SA_USER_ADMIN.SET_USER_LABELS('region_policy','sales_south','L3:E:R20,R40,R60,R80');
SA_USER_ADMIN.SET_USER_LABELS('region_policy','sales_east','L3:E:R60');
SA_USER_ADMIN.SET_USER_LABELS('region_policy','sales_west','L3:E:R80');

--EXEC LBACSYS.SA_USER_ADMIN.SET_DEFAULT_LABEL('REGION_POLICY', 'sales_manager', 'L3:M,E:R20,R40,R60,R80');


commit;
SELECT * FROM ADMIN_OLS.OLS_KHACHHANG;
show con_name;
GRANT EXECUTE ON LBACSYS.SA_UTL TO sales_manager;

SELECT * FROM USER_SA_USER_PRIVS WHERE USER_NAME = 'SALES_MANAGER';