
ALTER SESSION SET CONTAINER = ATBMCQ_16_CSDL;
SHOW CON_NAME;
-- 2. Xem danh sách tài khoản người dùng và role trong hệ thống Oracle DB Server.

SELECT role
FROM dba_roles
WHERE oracle_maintained = 'N'; -- SEE ONLY ROLES MANAGED BY THE USER (NOT BY ORACLE DB)

-- CREATE A USER TO TEST AS CLIENT
CREATE USER USER1 IDENTIFIED BY "321";
GRANT CREATE SESSION TO USER1;
GRANT EXECUTE ON IS_ADMIN_USER TO USER1;

SELECT *
FROM all_users where COMMON = 'NO';

