-- CONNECT AS SYSUSER
CREATE PLUGGABLE DATABASE ATBMCQ_16_CSDL
ADMIN USER ATBMCQ_ADMIN IDENTIFIED BY 123
ROLES = (DBA)
FILE_NAME_CONVERT = ('PDBSEED', 'ATBMCQ_16_CSDL');

ALTER PLUGGABLE DATABASE ATBMCQ_16_CSDL OPEN READ WRITE;
ALTER SESSION SET CONTAINER = ATBMCQ_16_CSDL;

--GRANT EXECUTE ANY PROCEDURE TO ATBMCQ_ADMIN;
GRANT CREATE SESSION TO ATBMCQ_ADMIN CONTAINER = CURRENT;

--GRANT INSERT ON ATBMCQ_ADMIN.EMPLOYEES TO ATBMCQ_ADMIN;
ALTER USER ATBMCQ_ADMIN QUOTA UNLIMITED ON SYSTEM;
GRANT CREATE ROLE TO ATBMCQ_ADMIN;

GRANT SELECT ON DBA_TAB_PRIVS TO ATBMCQ_ADMIN;
GRANT SELECT ON DBA_SYS_PRIVS TO ATBMCQ_ADMIN;
GRANT SELECT ON DBA_COL_PRIVS TO ATBMCQ_ADMIN;

GRANT CREATE USER TO ATBMCQ_ADMIN;

GRANT SELECT ON DBA_ROLES TO ATBMCQ_ADMIN;
GRANT SELECT ON DBA_ROLE_PRIVS TO ATBMCQ_ADMIN;
GRANT SELECT ON DBA_TS_QUOTAS TO ATBMCQ_ADMIN;
GRANT GRANT ANY PRIVILEGE TO ATBMCQ_ADMIN;
GRANT GRANT ANY ROLE TO ATBMCQ_ADMIN;
GRANT DROP USER TO ATBMCQ_ADMIN;
GRANT ALTER USER TO ATBMCQ_ADMIN;


-- CEATE VPD MANAGER
CREATE USER VPD_MGR IDENTIFIED BY 999321;

GRANT CREATE SESSION TO VPD_MGR;
GRANT CREATE PROCEDURE TO VPD_MGR;
GRANT EXECUTE ON DBMS_RLS TO VPD_MGR;
GRANT EXECUTE ANY PROCEDURE TO VPD_MGR;
GRANT EXECUTE ON DBMS_SESSION TO VPD_MGR;
GRANT EXECUTE ON DBMS_APPLICATION_INFO TO VPD_MGR;
GRANT DROP ANY PROCEDURE TO VPD_MGR;
GRANT UNLIMITED TABLESPACE TO VPD_MGR;

-- CUNG CẤP TOÀN QUYỀN TRÊN BẢNG SINHVIEN (4 QUYỀN), SELECT TRÊN NHANVIEN, DANGKY ĐỂ THỰC HIỆN VPD
GRANT SELECT, INSERT, UPDATE, DELETE ON ATBMCQ_ADMIN.SINHVIEN TO VPD_MGR;
GRANT SELECT ON ATBMCQ_ADMIN.NHANVIEN TO VPD_MGR;
GRANT SELECT ON ATBMCQ_ADMIN.DONVI TO VPD_MGR;


SELECT object_name, status
FROM dba_objects
WHERE object_name = 'PF_SINHVIEN_SELECT'
  AND owner = 'VPD_MGR';
  ALTER FUNCTION VPD_MGR.PF_SINHVIEN_SELECT COMPILE;

SHOW ERRORS FUNCTION VPD_MGR.PF_SINHVIEN_SELECT;
SHOW ERRORS FUNCTION PF_SINHVIEN_SELECT;
grant execute on vpd_mgr.pf_sinhvien_select to sv001;


SELECT VPD_MGR.PF_SINHVIEN_SELECT('ATBMCQ_ADMIN', 'SINHVIEN') FROM dual;
