CREATE PLUGGABLE DATABASE ATBMCQ_16_CSDL
ADMIN USER ATBMCQ_ADMIN IDENTIFIED BY 123
ROLES = (DBA)
FILE_NAME_CONVERT = ('PDBSEED', 'ATBMCQ_16_CSDL');

ALTER PLUGGABLE DATABASE ATBMCQ_16_CSDL OPEN READ WRITE;
COMMIT;
SHOW CON_NAME;
ALTER SESSION SET CONTAINER = ATBMCQ_16_CSDL;

GRANT EXECUTE ANY PROCEDURE TO ATBMCQ_ADMIN;
GRANT CREATE SESSION TO ATBMCQ_ADMIN CONTAINER = CURRENT;
GRANT CONNECT TO ATBMCQ_ADMIN;
GRANT SELECT ON DBA_ROLES TO ATBMCQ_ADMIN;
GRANT SELECT ON DBA_ROLE_PRIVS TO ATBMCQ_ADMIN;

-- ONLY INSIDE THE PDB
GRANT DROP USER TO ATBMCQ_ADMIN;
GRANT ALTER USER TO ATBMCQ_ADMIN;




GRANT SELECT ON DBA_TAB_PRIVS TO ATBMCQ_ADMIN;
GRANT SELECT ON DBA_SYS_PRIVS TO ATBMCQ_ADMIN;
GRANT SELECT ON DBA_ROLE_PRIVS TO ATBMCQ_ADMIN;

GRANT SELECT ON DBA_TS_QUOTAS TO ATBMCQ_ADMIN;
GRANT GRANT ANY PRIVILEGE TO ATBMCQ_ADMIN;
GRANT GRANT ANY ROLE TO ATBMCQ_ADMIN;