
CONNECT "ATBMCQ_ADMIN"/"123"@//localhost:1521/ATBMCQ_16_CSDL;

BEGIN
  FOR i IN 1..10 LOOP
    EXECUTE IMMEDIATE 'CREATE ROLE ROLE' || i;
  END LOOP;

  FOR i IN 1..10 LOOP
    EXECUTE IMMEDIATE 'CREATE USER USER' || i || ' IDENTIFIED BY 123';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO USER' || i;
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON ATBMCQ_ADMIN.IS_ADMIN_USER TO USER' || i;
  END LOOP;
END;
/

COMMIT;
DISCONNECT;
