SELECT * FROM ADMIN_OLS.THONGBAO;

VARIABLE x REFCURSOR;
EXEC :x := ADMIN_OLS.GET_ALL_LABELS;
PRINT x;

BEGIN
    -- Gán nhãn cho user 'ADMIN_OLS' với mã định danh 'u1'
    ADMIN_OLS.SET_OLS_LABEL_FOR_USER('U2', 'u2');
END;
/


BEGIN
    ADMIN_OLS.INSERT_THONGBAO('Thông báo hệ thống ngày từ nv001', 't2');
END;


SELECT USERNAME
FROM DBA_USERS
WHERE ORACLE_MAINTAINED = 'N';