CREATE PLUGGABLE DATABASE ATBMCQ_TEST_OLS
ADMIN USER ATBMCQ_TEST_OLS_ADMIN IDENTIFIED BY 123
ROLES = (DBA)
FILE_NAME_CONVERT = ('PDBSEED', 'ATBMCQ_TEST_OLS_PDB');

ALTER PLUGGABLE DATABASE ATBMCQ_TEST_OLS OPEN READ WRITE;

SHOW CON_NAME;
ALTER SESSION SET CONTAINER = ATBMCQ_TEST_OLS;
SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security';
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS';
---> BẬT OLS NẾU CHƯA BẬT/ CHƯA ĐĂNG KÝ THÌ ĐĂNG KÝ OLS VÀ BẬT OLS
-- This procedure registers Oracle Label Security.EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS; -- This procedure enables it
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
---> KHỞI ĐỘNG LẠI
SHUTDOWN IMMEDIATE;
STARTUP;

ALTER SESSION SET CONTAINER = CDB$ROOT;
---> UNLOCK LBACSYS (OLS ADMIN)
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;
---> NẾU CÓ RỒI THÌ MỞ PDB
ALTER PLUGGABLE DATABASE ATBMCQ_TEST_OLS OPEN READ WRITE;
---> CHUYỂN QUA PDB
ALTER SESSION SET CONTAINER= ATBMCQ_TEST_OLS;
SHOW CON_NAME;


--TẠO USER TEST OLS = ADMIN_OLS
---> TẠO ADMIN OLS & CẤP QUYỀN CHO ADMIN_OLS
grant lbacsys to admin_ols;
CREATE USER ADMIN_OLS IDENTIFIED BY 123 CONTAINER = CURRENT;
GRANT CONNECT,RESOURCE TO ADMIN_OLS; --CẤP QUYỀN CONNECT VÀ RESOURCE
GRANT UNLIMITED TABLESPACE TO ADMIN_OLS; --CẤP QUOTA CHO ADMIN_OLS
GRANT SELECT ANY DICTIONARY TO ADMIN_OLS; --CẤP QUYỀN ĐỌC DICTIONARY

---> CẤP QUYỀN EXECUTE CHO ADMIN_OLS
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_user_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_label_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON char_to_label TO ADMIN_OLS WITH GRANT OPTION;

---> ADD ADMIN_OLS VÀO LBAC_DBA
GRANT LBAC_DBA TO ADMIN_OLS;
GRANT EXECUTE ON sa_sysdba TO ADMIN_OLS;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN_OLS; -- CẤP QUYỀN THỰC THI



SELECT * FROM DBA_SA_LEVELS;
SELECT * FROM DBA_SA_COMPARTMENTS;
SELECT * FROM DBA_SA_GROUPS;
SELECT * FROM DBA_SA_GROUP_HIERARCHY;


-- Cấp thêm quyền tạo user, role, grant...
GRANT CREATE USER TO ADMIN_OLS CONTAINER = CURRENT;
GRANT ALTER USER TO ADMIN_OLS CONTAINER = CURRENT;
GRANT DROP USER TO ADMIN_OLS CONTAINER = CURRENT;

GRANT CREATE ROLE TO ADMIN_OLS CONTAINER = CURRENT;
GRANT GRANT ANY ROLE TO ADMIN_OLS CONTAINER = CURRENT;

--GRANT CREATE PROFILE TO ADMIN_OLS CONTAINER = CURRENT;
--GRANT ALTER PROFILE TO ADMIN_OLS CONTAINER = CURRENT;


SELECT * FROM DBA_SA_POLICIES WHERE POLICY_NAME = 'REGION_POLICY';


SELECT * FROM dba_registry WHERE comp_id = 'OLS';
SELECT * FROM DBA_OLS_STATUS;

SELECT VALUE FROM V$OPTION WHERE PARAMETER = 'Oracle Label Security'; 
SELECT COMP_NAME, STATUS, VERSION 
FROM DBA_REGISTRY 
WHERE COMP_NAME = 'Oracle Label Security'; 
show con_name;
--GRANT EXECUTE ON LBACSYS.SA_UTL TO ADMIN_OLS WITH GRANT OPTION;
